#name: Test on push
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: install python library
        run : |
          pip install pytest

      - name: install mysql docker instance
        run : |
          docker pull mysql/mysql-server:latest
          docker run --name=my_mysql --restart on-failure -d mysql/mysql-server:latest

      - name: multiline script
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" 
          git config --global user.email "willyam.guilleron@gmail.com"
          git config --global user.name "Willyam33"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          cd python_files
          #cd essai_pytest
          pytest >> ../logs/log_pytest.txt
          cat ../logs/log_pytest.txt
          #git add ../logs/log_pytest.txt
          #git commit -m "remontee des logs pytest"
          #git push